### ISSUE TITLE
[feature request] Add support DJ role

### ISSUE THREAD

**Issue by negezor** [TheTipo01/YADMB#14]
Hello. How about adding support for the DJ role? It would make my life much easier. I constantly have to add people to the blacklist in the morning who abuse the bot queue.

**Comment by TheTipo01** [comment]
Hello!
I added the blacklist function only to annoy a friend of mine over the music he queued up :D

Anyway, I was thinking about adding a config option to specify:
1) if you want to enable the DJ role "system"
2) what commands can only be used by someone with the DJ role

As for the role itself, searching at startup for a role with the name "DJ" should be fine, and for the servers whose role has not been configured, watch if a role with the name DJ is created.

If you have some considerations, i'm happy to listen to them!

**Comment by negezor** [comment]
I think we can borrow settings from one of the bots.
![image](https://github.com/TheTipo01/YADMB/assets/9392723/708d929f-31f9-4a45-b0ae-4bdc1f6ef800)

I think we can distinguish two tasks for implementation:
1. Setting up DJ roles via select. Since the name of the DJ will not always be available on the theme servers.
2. Turning on and off DJ mode.

In DJ mode, only the DJ and bot admin can add to the bot queue. I think this is more than enough for 90% coverage.

**Comment by TheTipo01** [comment]
The latest commit implements everything.
I tested it enough, but please tell me if you find any bugs!
