### ISSUE TITLE
Document process of adding the bot

### ISSUE THREAD

**Issue by mpldr** [TheTipo01/YADMB#18]
Hi there o/

I am not sure what permissions the bot specifically requires… could you help me with that?

It might also be useful to document the OAuth2 Address for those less familiar with the process :)

**Comment by TheTipo01** [comment]
Hi, I created a [page](https://github.com/TheTipo01/YADMB/wiki/Creating-and-adding-the-bot-to-your-server) in the wiki documenting everything.
It should cover everything, tell me what you think!

**Comment by mpldr** [comment]
Thanks, at least I'd know what to do :D, thanks I just removed 3 or
4 permissions from my bot.
-- 
Moritz Poldrack
https://moritz.sh
