### ISSUE TITLE
No song plays

### ISSUE THREAD

**Issue by AriaFantom** [TheTipo01/YADMB#9]
`Can't get info about song: OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Not found '_raw_ecb.cpython-38-aarch64-linux-gnu.so', Cannot load '_raw_ecb.abi3.so': /snap/yt-dlp/19/lib/python3.8/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Not found '_raw_ecb.so'`

i am using raspberry pi

**Comment by AriaFantom** [comment]
After installing all deps it still there

**Comment by TheTipo01** [comment]
Hi there!

If you have installed all the dependencies, the one that usually gave me problems was dca.
As you build it using go get, the executable is usually in your $GOPATH/bin directory.
This directory is probably not in your path, and the bot can't find it, throwing random (and cryptic) errors.

I suggest you make a symlink of the executable from that directory to /usr/bin
Example: `ln -s /home/thetipo01/go/bin/dca /usr/bin/dca`

If you do have a working docker install on your raspberry, you can also use that without worrying about these things.


Also, will be working on a commit to print which dependency the bot can't find, so you can diagnose the problem better!
